### ISSUE TITLE
Show zopectl.command commands as well

### ISSUE THREAD

**Issue by gforcada** [plone/plone.recipe.zope2instance#18]
p.r.zope2instance can show and run commands defined on setup.py like this:

```
[plone.recipe.zope2instance.ctl]
solr_clear_index=collective.solr.commands:solr_clear_index
solr_reindex=collective.solr.commands:solr_reindex
```

Actually it can also run (but **not** display them on its help) any command defined like:

```
[zopectl.command]
solr_clear_index=collective.solr.commands:solr_clear_index
solr_reindex=collective.solr.commands:solr_reindex
```

It would be great if the help command could also show them as well.

If not one is puzzled about installing a distribution (collective.solr for example) that claims to install some commands but that are not shown at all when running ``bin/instance help``.

Is there any reason to not show them?

**Comment by jensens** [comment]
+1

**Comment by tschorr** [comment]
Looking at the example, wouldn't it be easier to change the entry point to p.r.zope2instance.ctl in collective.solr? This would also bypass the issues I have described here: https://github.com/collective/collective.solr/pull/88#issuecomment-154019028.

**Comment by gforcada** [comment]
@tschorr sure, that would  be a fix for collective.solr, but I guess collective.solr is not the only package that provides commands, so if instead of having to fix all and every single distribution (and get a release for each of them), we list all commands we only have to care about a single package to fix and release.

**Comment by tschorr** [comment]
I cannot find many packages that use `zopectl.command`, but I might be mistaken.

In my opinion it is rather confusing that there are two different entry point names for exactly the same functionality.
`p.r.zope2instance` overrides much of the functionality of `Zope2.Startup.zopectl`, but instead of overriding the existing entry point configuration, it defines a new entry point that does the same thing (although arguably better, as you have noted).
I didn't notice that there was another entry point definition when working on the `collective.solr` PR recently, otherwise I would have changed the entry point to `p.r.zope2instance.ctl` back then.

So this now might be a good chance to simplify things and maybe get rid of one of the two entry points. Or at least put some deprecation warning for the `zopectl.command` case.
