### ISSUE TITLE
ImportError: No module named recipe.zope2instance.ctl

### ISSUE THREAD

**Issue by diti76** [plone/plone.recipe.zope2instance#21]
I get the following error:
Traceback (most recent call last):
  File "./bin/client2", line 252, in <module>
    import plone.recipe.zope2instance.ctl
ImportError: No module named recipe.zope2instance.ctl

allthough I have
../buildout-cache/eggs/plone.recipe.zope2instance-4.2.18-py2.7.egg/
and the above folder is correctly added to  sys.path[0:0].
I m using python is 2.7.6

Can not figure out what the problem here might be

**Comment by zmijunkie** [comment]
Same here but on python 2.7.13, also 
import plone.recipe.zeoserver.ctl
does not work

**Comment by mauritsvanrees** [comment]
Hard to say where the exact problem is. Sometimes this fails because you have zope or plone packages installed in your main Python environment (happens for `zope.interface` on several systems).
Some things to try:

- newest `zc.buildout` and `setuptools` versions
- older `zc.buildout` and `setuptools` versions (`zc.buildout 2.5.3` and `setuptools 33.1.1` are pretty stable versions in my experience)
- if you are using `bootstrap.py` to create a `bin/buildout` script: try using a `virtualenv` and `bin/pip install zc.buildout` instead
- if you are using a virtualenv: try using `bootstrap.py` instead

Yes, these are conflicting things to try...

**Comment by tkimnguyen** [comment]
In my case, rerunning buildout fixed the problem, which I think was caused by my having renamed my ~/.buildout directory (so that I would no longer be using my local buildout cache). It makes sense that running bin/instance didn't work for me, since I'd moved the eggs it depended on.

**Comment by jugmac00** [comment]
Today, I also suffered from this bug - thanks @tkimnguyen - your suggestion worked for me, too.

**Comment by silviot** [comment]
For me this was caused by packages installed by mistake in a virtualenv and in the user directory (with `pip install --user`).

Uninstalling them solved the issue. This is the command I used:
```
yes | pip uninstall (pip freeze|egrep 'plone|zope'|sed 's/==.*//')
```
